version: '3.8'

services:
  web:
    build: .
    image: aass-sample-service:latest
    container_name: aass-sample-service
    command: pipenv run python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/aass-sample-service/
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - local
      - aass_network

  db:
    image: postgres:13.0-alpine
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - local

volumes:
  database-data:

networks:
  aass_network:
    external:
      name: aass_network
  local:
    driver: bridge
